# Generated by Django 5.2.12 on 2026-05-31 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(db_index=True, max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(max_length=500)),
                ('icon', models.CharField(default='bell', max_length=40)),
                ('notification_type', models.CharField(blank=True, max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='dashboard_d_user_id_49537d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'source_key'), name='unique_dashboard_notification_per_user_source')],
            },
        ),
    ]
