# Generated by Django 5.2.14 on 2026-05-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
