# Generated by Django 5.2.12 on 2026-05-28 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_employee_profile_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_employee_id_per_org',
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_assigned_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
