# Generated by Django 5.2.12 on 2026-05-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_unique_employee_id_per_org_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0004_organization_organization_type_other_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_id', ''), _negated=True), fields=('organization', 'employee_id'), name='unique_employee_id_per_org'),
        ),
    ]
