# Generated by Django 5.2.12 on 2026-05-28 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_restore_employee_id_constraint'),
        ('attendance', '0002_workshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='attendance.workshift'),
        ),
    ]
