# Generated by Django 5.2.12 on 2026-05-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_login_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_unit',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
