# Generated by Django 5.2.12 on 2026-05-29 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_business_unit'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='grades.grade'),
        ),
        migrations.AddField(
            model_name='user',
            name='org_designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holders', to='grades.designation'),
        ),
        migrations.AlterField(
            model_name='loginauditlog',
            name='portal',
            field=models.CharField(choices=[('admin', 'Organization Admin Portal'), ('hr', 'HR Portal'), ('employee', 'Employee Portal')], max_length=20),
        ),
    ]
