# Generated by Django 5.2.12 on 2026-05-29 19:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_job_grade_user_org_designation_and_more'),
        ('organizations', '0005_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PROBATION', 'Probation'), ('NOTICE', 'Notice period'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('DEACTIVATE', 'Deactivated'), ('ACTIVATE', 'Activated'), ('STATUS_CHANGE', 'Status changed'), ('BULK', 'Bulk action'), ('PASSWORD_RESET', 'Password reset')], max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_audit_logs', to='organizations.organization')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
