# Generated by Django 5.2.12 on 2026-06-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='esi_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='pf_account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='uan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
