# Generated by Django 5.2.14 on 2026-06-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_esi_number_user_pf_account_number_and_more'),
        ('attendance', '0007_alter_attendancerecord_status_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('grades', '0002_alter_gradepermission_permission_key'),
        ('organizations', '0010_organization_attendance_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Organization Admin'), ('HR', 'HR'), ('MANAGER', 'Manager / Team Leader'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'reporting_manager'], name='user_org_reporting_mgr_idx'),
        ),
    ]
