# Generated by Django 5.2.14 on 2026-06-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_role_user_user_org_reporting_mgr_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginauditlog',
            name='portal',
            field=models.CharField(choices=[('admin', 'Organization Admin Portal'), ('hr', 'HR Portal'), ('manager', 'Manager / Team Leader Portal'), ('employee', 'Employee Portal')], max_length=20),
        ),
    ]
