# Generated by Django 5.2.14 on 2026-06-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_manager_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_compliance',
            field=models.BooleanField(default=False),
        ),
    ]
