# Generated by Django 5.2.12 on 2026-05-28 17:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('half_day', models.CharField(choices=[('NONE', 'Full day(s)'), ('FIRST_HALF', 'First half'), ('SECOND_HALF', 'Second half')], default='NONE', max_length=20)),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('emergency_contact', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.PositiveSmallIntegerField(help_text='1=Manager, 2=HR, 3=Final')),
                ('step_label', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leaves.leaverequest')),
            ],
            options={
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(max_length=40)),
                ('color', models.CharField(default='#8b5cf6', max_length=20)),
                ('annual_quota', models.DecimalField(decimal_places=1, default=Decimal('12'), max_digits=5)),
                ('carry_forward_max', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('accrual_monthly', models.BooleanField(default=False, help_text='Accrue quota monthly instead of yearly lump sum.')),
                ('gender_eligibility', models.CharField(choices=[('ALL', 'All employees'), ('MALE', 'Male only'), ('FEMALE', 'Female only')], default='ALL', max_length=10)),
                ('requires_attachment', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='organizations.organization')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leaves.leavetype'),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('allocated', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6)),
                ('used', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6)),
                ('carried_forward', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leaves.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('NATIONAL', 'National'), ('COMPANY', 'Company'), ('OPTIONAL', 'Optional'), ('FESTIVAL', 'Festival'), ('REGIONAL', 'Regional')], default='COMPANY', max_length=20)),
                ('branch', models.CharField(blank=True, help_text='Blank = all branches', max_length=120)),
                ('is_optional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='organizations.organization')),
            ],
            options={
                'ordering': ['date', 'name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'date', 'name'), name='unique_holiday_per_org_date_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_leave_type_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('user', 'leave_type', 'year'), name='unique_leave_balance_per_user_type_year'),
        ),
    ]
