# Generated by Django 5.2.14 on 2026-06-11 18:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_gradepermission_permission_key'),
        ('leaves', '0002_leavetype_quota_nullable'),
        ('organizations', '0011_organization_leave_auto_approve_without_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='adjusted',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Manual HR/Admin adjustment (positive or negative).', max_digits=6),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='applicable_departments',
            field=models.ManyToManyField(blank=True, related_name='leave_types', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='applicable_designations',
            field=models.ManyToManyField(blank=True, related_name='leave_types', to='grades.designation'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='applicable_to',
            field=models.CharField(choices=[('ALL', 'All employees'), ('DEPARTMENT', 'Specific departments'), ('DESIGNATION', 'Specific designations')], default='ALL', help_text='Which employees may use this leave type.', max_length=20),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
