# Generated by Django 5.2.14 on 2026-08-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_attendanceleavededuction_no_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceleavededuction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
