# Generated by Django 5.2.14 on 2026-06-28 17:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0018_shiftchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_can_manage', models.BooleanField(default=True)),
                ('hr_can_manage', models.BooleanField(default=True)),
                ('admin_can_generate', models.BooleanField(default=True)),
                ('hr_can_generate', models.BooleanField(default=True)),
                ('employee_can_generate', models.BooleanField(default=False)),
                ('admin_can_view_all', models.BooleanField(default=True)),
                ('hr_can_view_all', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Document Permission',
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(choices=[('OFFER', 'Offer Letter'), ('APPOINTMENT', 'Appointment Letter'), ('EXPERIENCE', 'Experience Letter'), ('RELIEVING', 'Relieving Letter'), ('PROMOTION', 'Promotion Letter'), ('INCREMENT', 'Increment Letter'), ('WARNING', 'Warning Letter'), ('SALARY_CERT', 'Salary Certificate')], max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(help_text='HTML body with {{placeholders}}')),
                ('is_active', models.BooleanField(default=True)),
                ('include_logo', models.BooleanField(default=True)),
                ('include_signature_placeholder', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_versions_saved', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.documenttemplate')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(choices=[('OFFER', 'Offer Letter'), ('APPOINTMENT', 'Appointment Letter'), ('EXPERIENCE', 'Experience Letter'), ('RELIEVING', 'Relieving Letter'), ('PROMOTION', 'Promotion Letter'), ('INCREMENT', 'Increment Letter'), ('WARNING', 'Warning Letter'), ('SALARY_CERT', 'Salary Certificate')], max_length=30)),
                ('template_name', models.CharField(max_length=200)),
                ('resolved_body', models.TextField()),
                ('pdf_file', models.FileField(blank=True, upload_to='documents/generated/%Y/%m/')),
                ('extra_context', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_generated_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='organizations.organization')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='documents.documenttemplate')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE_TEMPLATE', 'Created template'), ('EDIT_TEMPLATE', 'Edited template'), ('DELETE_TEMPLATE', 'Deleted template'), ('RESTORE_VERSION', 'Restored version'), ('GENERATE_DOC', 'Generated document'), ('DOWNLOAD_DOC', 'Downloaded document'), ('DELETE_DOC', 'Deleted document'), ('UPDATE_PERMISSIONS', 'Updated permissions')], max_length=30)),
                ('summary', models.CharField(max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_audit_logs', to='organizations.organization')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='documents.documenttemplate')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='documents.generateddocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
