# Generated by Django 5.2.12 on 2026-05-29 18:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_department'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('monthly_price_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('setup_fee_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_employee_price_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trial_days', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, default='puzzle', max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='plan',
            name='branch_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Null = unlimited', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='feature_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plan',
            name='per_employee_price_inr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Optional per-employee surcharge', max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='setup_fee_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='storage_limit_mb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveSmallIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='subscription',
            name='credit_balance_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='limit_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_inr',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('PAID', 'Paid'), ('VOID', 'Void'), ('UNCOLLECTIBLE', 'Uncollectible'), ('WAIVED', 'Waived')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='plan',
            name='monthly_price_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='plan',
            name='yearly_price_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='TRIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='subscriptions.subscription'),
        ),
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('PLAN_CHANGE', 'Plan change'), ('SUBSCRIPTION_ACTIVATE', 'Subscription activated'), ('SUBSCRIPTION_SUSPEND', 'Subscription suspended'), ('SUBSCRIPTION_RENEW', 'Subscription renewed'), ('INVOICE_GENERATED', 'Invoice generated'), ('INVOICE_WAIVED', 'Invoice waived'), ('PAYMENT_RECORDED', 'Payment recorded'), ('PAYMENT_FAILED', 'Payment failed'), ('REFUND', 'Refund'), ('COUPON_APPLIED', 'Coupon applied'), ('CREDIT_ADDED', 'Credit added'), ('ADDON_ACTIVATED', 'Add-on activated'), ('ADDON_DEACTIVATED', 'Add-on deactivated'), ('TRIAL_EXTENDED', 'Trial extended'), ('MANUAL_OVERRIDE', 'Manual override')], max_length=40)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_audit_logs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIAL_REFUND', 'Partial refund')], default='PENDING', max_length=20)),
                ('method', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank transfer'), ('MANUAL', 'Manual / offline')], default='MANUAL', max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=120)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('refund_amount_inr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_assignments', to='subscriptions.addoncatalog')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_addons', to='organizations.organization')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_addons', to='subscriptions.subscription')),
            ],
            options={
                'unique_together': {('organization', 'addon')},
            },
        ),
    ]
