# Generated by Django 5.2.12 on 2026-05-30 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_addoncatalog_invoice_discount_inr_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('url_names', models.JSONField(blank=True, default=list, help_text='Django URL names gated by this feature (for upgrade prompts).')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='addoncatalog',
            name='feature_keys',
            field=models.JSONField(blank=True, default=list, help_text='Feature keys unlocked when this add-on is purchased.'),
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_assignments', to='subscriptions.featuredefinition')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='subscriptions.plan')),
            ],
            options={
                'ordering': ['feature__sort_order', 'feature__name'],
                'unique_together': {('plan', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='PlanMenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('icon', models.CharField(default='circle', max_length=40)),
                ('url_name', models.CharField(max_length=120)),
                ('query_string', models.CharField(blank=True, max_length=200)),
                ('feature_key', models.CharField(blank=True, max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('audience', models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR'), ('EMPLOYEE', 'Employee')], default='ADMIN', max_length=20)),
                ('active_views', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='subscriptions.plan')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'indexes': [models.Index(fields=['plan', 'audience', 'sort_order'], name='subscriptio_plan_id_eb5dba_idx')],
            },
        ),
    ]
