# Generated by Django 5.2.12 on 2026-05-30 12:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_department'),
        ('subscriptions', '0003_plan_feature_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='box', max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_globally_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='featuredefinition',
            name='depends_on',
            field=models.JSONField(blank=True, default=list, help_text='Feature keys that must be enabled before this feature can be enabled.'),
        ),
        migrations.AddField(
            model_name='featuredefinition',
            name='feature_type',
            field=models.CharField(choices=[('FEATURE', 'Feature'), ('PAGE', 'Page'), ('FIELD', 'Field'), ('WORKFLOW', 'Workflow')], default='FEATURE', max_length=20),
        ),
        migrations.AddField(
            model_name='featuredefinition',
            name='is_globally_enabled',
            field=models.BooleanField(default=True, help_text='When False, feature is disabled platform-wide regardless of plan.'),
        ),
        migrations.CreateModel(
            name='FeatureControlAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('GLOBAL_ENABLE', 'Global enable'), ('GLOBAL_DISABLE', 'Global disable'), ('PLAN_ENABLE', 'Plan enable'), ('PLAN_DISABLE', 'Plan disable'), ('ORG_OVERRIDE', 'Organization override'), ('ORG_OVERRIDE_CLEAR', 'Organization override cleared'), ('NAV_UPDATE', 'Navigation updated'), ('PAGE_UPDATE', 'Page updated'), ('MODULE_UPDATE', 'Module updated'), ('ADDON_TOGGLE', 'Add-on toggled'), ('LIMIT_UPDATE', 'Limit updated'), ('ROLE_PERMISSION', 'Role permission updated'), ('FIELD_UPDATE', 'Field visibility updated'), ('BULK_ACTION', 'Bulk action')], max_length=30)),
                ('feature_key', models.CharField(blank=True, max_length=80)),
                ('summary', models.CharField(max_length=255)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_control_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_control_logs', to='organizations.organization')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='featuredefinition',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='subscriptions.featuremodule'),
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('form_context', models.CharField(blank=True, help_text='e.g. employee_form', max_length=80)),
                ('is_globally_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='subscriptions.featuredefinition')),
            ],
            options={
                'ordering': ['form_context', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('icon', models.CharField(default='circle', max_length=40)),
                ('url_name', models.CharField(max_length=120)),
                ('query_string', models.CharField(blank=True, max_length=200)),
                ('feature_key', models.CharField(blank=True, max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('audience', models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR'), ('EMPLOYEE', 'Employee')], default='ADMIN', max_length=20)),
                ('active_views', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, help_text='Null = global default navigation template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='subscriptions.plan')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationFeatureOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_overrides', to='subscriptions.featuredefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='organizations.organization')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_overrides_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationFieldOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_overrides', to='subscriptions.fielddefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_overrides', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_limit_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('branch_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('admin_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('hr_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('api_limit_daily', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_limits', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationNavigationOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('navigation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_overrides', to='subscriptions.navigationitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_overrides', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PageDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('url_name', models.CharField(max_length=120)),
                ('is_globally_enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='subscriptions.featuredefinition')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='subscriptions.featuremodule')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureRolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Organization Admin'), ('HR', 'HR'), ('EMPLOYEE', 'Employee')], max_length=20)),
                ('is_allowed', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='subscriptions.featuredefinition')),
            ],
            options={
                'ordering': ['feature__sort_order', 'role'],
                'unique_together': {('feature', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='navigationitem',
            index=models.Index(fields=['plan', 'audience', 'sort_order'], name='subscriptio_plan_id_a4fb16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationfeatureoverride',
            unique_together={('organization', 'feature')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationfieldoverride',
            unique_together={('organization', 'field')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationnavigationoverride',
            unique_together={('organization', 'navigation_item')},
        ),
    ]
