# Generated by Django 5.2.12 on 2026-05-30 12:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_master_feature_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(default='folder', max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Feature categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='featuredefinition',
            name='api_path_prefix',
            field=models.CharField(blank=True, help_text='API path prefix blocked when disabled, e.g. /api/recruitment/', max_length=120),
        ),
        migrations.AddField(
            model_name='featuredefinition',
            name='icon',
            field=models.CharField(blank=True, default='circle', max_length=40),
        ),
        migrations.AddField(
            model_name='featuredefinition',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='subscriptions.featuredefinition'),
        ),
        migrations.AddField(
            model_name='featuredefinition',
            name='path_prefix',
            field=models.CharField(blank=True, help_text='URL path prefix blocked when disabled, e.g. /recruitment/', max_length=120),
        ),
        migrations.AddField(
            model_name='featuredefinition',
            name='display_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='subscriptions.featurecategory'),
        ),
    ]
