# Generated by Django 5.2.14 on 2026-06-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_admin_nav_core_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerolepermission',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Organization Admin'), ('HR', 'HR'), ('MANAGER', 'Manager / Team Leader'), ('EMPLOYEE', 'Employee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='audience',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='ADMIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='planmenuitem',
            name='audience',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='ADMIN', max_length=20),
        ),
    ]
