# Generated by Django 5.2.14 on 2026-07-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_remove_manager_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='group_label',
            field=models.CharField(blank=True, help_text='When set, items sharing this label render as a collapsible sidebar section instead of a flat item.', max_length=40),
        ),
        migrations.AddField(
            model_name='planmenuitem',
            name='group_label',
            field=models.CharField(blank=True, help_text='When set, items sharing this label render as a collapsible sidebar section instead of a flat item.', max_length=40),
        ),
    ]
