# Generated by Django 5.2.14 on 2026-07-16 16:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_navigationitem_group_label_planmenuitem_group_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('yearly_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('17'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billing settings',
                'verbose_name_plural': 'Billing settings',
            },
        ),
    ]
