# Generated by Django 5.2.14 on 2026-07-11 04:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0018_shiftchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('trigger_event', models.CharField(choices=[('ATTENDANCE_MARKED', 'Attendance marked'), ('LEAVE_REQUESTED', 'Leave requested'), ('SCHEDULED', 'Scheduled (batch)'), ('MANUAL', 'Manual only')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('DRAFT', 'Draft')], default='DRAFT', max_length=10)),
                ('priority', models.IntegerField(default=100, help_text='Lower number runs first.')),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('is_test_mode', models.BooleanField(default=False, help_text='When on, the rule evaluates and logs but actions never mutate real data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(blank=True, max_length=32)),
                ('subject_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_approvals_to_review', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_approval_requests', to='organizations.organization')),
                ('requested_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_approvals_requested_for', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='ruleengine.rule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Rule created'), ('UPDATED', 'Rule updated'), ('ENABLED', 'Rule enabled'), ('DISABLED', 'Rule disabled'), ('DELETED', 'Rule deleted'), ('PRIORITY_CHANGED', 'Rule priority changed'), ('TESTED', 'Rule tested (dry run)')], max_length=20)),
                ('object_id', models.UUIDField(blank=True, help_text='PK of the affected rule.', null=True)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_audit_logs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name_snapshot', models.CharField(blank=True, max_length=150)),
                ('trigger_event', models.CharField(choices=[('ATTENDANCE_MARKED', 'Attendance marked'), ('LEAVE_REQUESTED', 'Leave requested'), ('SCHEDULED', 'Scheduled (batch)'), ('MANUAL', 'Manual only')], max_length=20)),
                ('subject_type', models.CharField(blank=True, max_length=32)),
                ('subject_id', models.CharField(blank=True, max_length=64)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('matched', models.BooleanField(default=False)),
                ('is_test_run', models.BooleanField(default=False)),
                ('actions_result', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_execution_logs', to='organizations.organization')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='ruleengine.rule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['organization', 'trigger_event', 'status'], name='rule_org_trigger_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['organization', 'priority'], name='rule_org_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleauditlog',
            index=models.Index(fields=['organization', '-created_at'], name='rule_audit_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleexecutionlog',
            index=models.Index(fields=['organization', '-created_at'], name='rule_exec_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleexecutionlog',
            index=models.Index(fields=['rule', '-created_at'], name='rule_exec_rule_created_idx'),
        ),
    ]
