# Generated by Django 5.2.14 on 2026-06-11 17:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0010_organization_attendance_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamActionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LEAVE_APPROVE', 'Leave approved'), ('LEAVE_REJECT', 'Leave rejected'), ('REGULARIZATION_APPROVE', 'Attendance regularization approved'), ('REGULARIZATION_REJECT', 'Attendance regularization rejected')], max_length=32)),
                ('object_id', models.UUIDField(blank=True, help_text='PK of the affected leave request / regularization request.', null=True)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The manager who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_action_audit_logs', to='organizations.organization')),
                ('target_user', models.ForeignKey(blank=True, help_text='The employee the action was taken on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'team action audit log',
                'verbose_name_plural': 'team action audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='team_audit_org_created_idx'), models.Index(fields=['actor', '-created_at'], name='team_audit_actor_created_idx')],
            },
        ),
    ]
