# Generated by Django 5.2.14 on 2026-06-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamactionauditlog',
            name='action',
            field=models.CharField(choices=[('LEAVE_APPROVE', 'Leave approved'), ('LEAVE_REJECT', 'Leave rejected'), ('LEAVE_APPLY', 'Leave applied'), ('LEAVE_CANCEL', 'Leave cancelled'), ('BALANCE_ADJUST', 'Leave balance adjusted'), ('REGULARIZATION_APPROVE', 'Attendance regularization approved'), ('REGULARIZATION_REJECT', 'Attendance regularization rejected')], max_length=32),
        ),
    ]
