# Generated by Django 5.2.12 on 2026-05-29 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('level_number', models.PositiveSmallIntegerField(default=5, help_text='1 = highest seniority')),
                ('category', models.CharField(choices=[('HR', 'HR Grades'), ('EMPLOYEE', 'Employee Grades'), ('MANAGEMENT', 'Management Grades'), ('EXECUTIVE', 'Executive Grades'), ('TECHNICAL', 'Technical Grades'), ('CONTRACTUAL', 'Contractual Grades')], default='EMPLOYEE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('priority_order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('salary_band_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_band_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departments', models.ManyToManyField(blank=True, related_name='linked_grades', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_grades', to='organizations.organization')),
                ('parent_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_grades', to='grades.grade')),
                ('reporting_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_from', to='grades.grade')),
            ],
            options={
                'ordering': ['category', 'level_number', 'priority_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('priority_order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='organizations.organization')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='grades.grade')),
            ],
            options={
                'ordering': ['priority_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CareerPathStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('requirements', models.TextField(blank=True, help_text='Eligibility criteria for promotion')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_path_steps', to='organizations.organization')),
                ('from_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_from_steps', to='grades.grade')),
                ('to_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_to_steps', to='grades.grade')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='GradeChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_changes_made', to=settings.AUTH_USER_MODEL)),
                ('from_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='grades.grade')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('to_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='grades.grade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_key', models.CharField(choices=[('hr.full', 'Full HR access'), ('hr.limited', 'Limited HR access'), ('attendance.view', 'View attendance'), ('attendance.manage', 'Manage attendance'), ('leave.approve', 'Approve leave'), ('payroll.view', 'View payroll'), ('payroll.manage', 'Manage payroll'), ('team.approve', 'Team approval access'), ('recruitment.manage', 'Recruitment access'), ('reports.view', 'View reports')], max_length=40)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='grades.grade')),
            ],
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['organization', 'category', 'status'], name='grades_grad_organiz_ab0510_idx'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('organization', 'code'), name='unique_grade_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='designation',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('organization', 'code'), name='unique_designation_code_per_org'),
        ),
        migrations.AlterUniqueTogether(
            name='careerpathstep',
            unique_together={('organization', 'from_grade', 'to_grade')},
        ),
        migrations.AlterUniqueTogether(
            name='gradepermission',
            unique_together={('grade', 'permission_key')},
        ),
    ]
