# Generated by Django 5.2.14 on 2026-06-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradepermission',
            name='permission_key',
            field=models.CharField(choices=[('hr.full', 'Full HR access'), ('hr.limited', 'Limited HR access'), ('attendance.view', 'View attendance'), ('attendance.manage', 'Manage attendance'), ('leave.approve', 'Approve leave'), ('payroll.view', 'View payroll'), ('payroll.manage', 'Manage payroll'), ('team.approve', 'Team approval access'), ('reports.view', 'View reports')], max_length=40),
        ),
    ]
