# Generated by Django 5.2.12 on 2026-05-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_workshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='attendance_source',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('WEB', 'Web portal'), ('MOBILE', 'Mobile app'), ('BIOMETRIC', 'Biometric')], default='WEB', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='break_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
