# Generated by Django 5.2.12 on 2026-05-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_source_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='branch',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='workshift',
            name='break_minutes',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='workshift',
            name='color',
            field=models.CharField(default='#8b5cf6', max_length=7),
        ),
        migrations.AddField(
            model_name='workshift',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workshift',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshift',
            name='night_allowance_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='workshift',
            name='shift_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='workshift',
            name='shift_type',
            field=models.CharField(choices=[('GENERAL', 'General Shift'), ('MORNING', 'Morning Shift'), ('EVENING', 'Evening Shift'), ('NIGHT', 'Night Shift'), ('ROTATIONAL', 'Rotational Shift'), ('FLEXIBLE', 'Flexible Shift'), ('SPLIT', 'Split Shift'), ('WFH', 'Work From Home Shift')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='workshift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workshift',
            name='weekly_off_days',
            field=models.CharField(blank=True, help_text='Comma-separated weekday numbers (0=Mon … 6=Sun).', max_length=20),
        ),
    ]
