# Generated by Django 5.2.12 on 2026-06-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_breakrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half day'), ('LEAVE', 'On leave'), ('WFH', 'Work from home'), ('HOLIDAY', 'Holiday'), ('WEEKEND_OFF', 'Weekend Off')], default='PRESENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendanceregularizationrequest',
            name='requested_status',
            field=models.CharField(blank=True, choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half day'), ('LEAVE', 'On leave'), ('WFH', 'Work from home'), ('HOLIDAY', 'Holiday'), ('WEEKEND_OFF', 'Weekend Off')], max_length=20),
        ),
    ]
