# Generated by Django 5.2.12 on 2026-05-28 17:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tenure_months', models.PositiveSmallIntegerField(default=12)),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DEFAULTED', 'Defaulted')], default='ACTIVE', max_length=12)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('LOCKED', 'Locked')], default='DRAFT', max_length=12)),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_reimbursements', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='organizations.organization')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PayrollApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(choices=[('HR', 'HR Approval'), ('FINANCE', 'Finance Approval'), ('DIRECTOR', 'Director Approval')], max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='payroll.payrollrun')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('reimbursements', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('leave_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('attendance_days', models.PositiveSmallIntegerField(default=0)),
                ('working_days', models.PositiveSmallIntegerField(default=0)),
                ('leave_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('bank_reference', models.CharField(blank=True, max_length=60)),
                ('payslip_number', models.CharField(blank=True, max_length=40)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('TRAVEL', 'Travel'), ('FOOD', 'Food'), ('INTERNET', 'Internet / Mobile'), ('MEDICAL', 'Medical'), ('OTHER', 'Other')], default='OTHER', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='reimbursements/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements', to='payroll.payrollrun')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=80)),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], max_length=12)),
                ('category', models.CharField(choices=[('BASIC', 'Basic Salary'), ('HRA', 'HRA'), ('SPECIAL', 'Special Allowance'), ('MEDICAL', 'Medical Allowance'), ('TRAVEL', 'Travel Allowance'), ('BONUS', 'Bonus'), ('INCENTIVE', 'Incentives'), ('OVERTIME', 'Overtime'), ('PF', 'Provident Fund'), ('ESI', 'ESI'), ('PT', 'Professional Tax'), ('TAX', 'Income Tax'), ('LOAN', 'Loan Deduction'), ('OTHER', 'Other')], default='OTHER', max_length=12)),
                ('calc_type', models.CharField(choices=[('FIXED', 'Fixed amount'), ('PCT_BASIC', '% of Basic'), ('PCT_GROSS', '% of Gross')], default='FIXED', max_length=12)),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('default_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_statutory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='organizations.organization')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('line_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payslip')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.salarycomponent')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_revisions_approved', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_revisions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(max_length=40)),
                ('grade', models.CharField(blank=True, max_length=40)),
                ('monthly_ctc', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_structures', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salary_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('HOURLY', 'Hourly'), ('CONTRACT', 'Contract')], default='MONTHLY', max_length=12)),
                ('monthly_ctc', models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_profiles', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_assignments', to='payroll.salarystructure')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_lines', to='payroll.salarycomponent')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.salarystructure')),
            ],
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year_start', models.DateField()),
                ('regime', models.CharField(default='NEW', max_length=20)),
                ('standard_deduction', models.DecimalField(decimal_places=2, default=Decimal('75000'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_configs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-financial_year_start'],
            },
        ),
        migrations.CreateModel(
            name='TaxSlab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tax_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='payroll.taxconfiguration')),
            ],
            options={
                'ordering': ['min_income'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('organization', 'year', 'month'), name='unique_payroll_run_per_org_month'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('payroll_run', 'user'), name='unique_payslip_per_run_user'),
        ),
        migrations.AddConstraint(
            model_name='salarycomponent',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_salary_component_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_salary_structure_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='salarystructureline',
            constraint=models.UniqueConstraint(fields=('structure', 'component'), name='unique_structure_component_line'),
        ),
    ]
