# Generated by Django 5.2.12 on 2026-06-09 18:59

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], default='EARNING', max_length=12)),
                ('mode', models.CharField(choices=[('FIXED', 'Fixed amount'), ('PCT_CTC', '% of CTC'), ('PCT_BASIC', '% of Basic')], default='FIXED', max_length=12)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.employeesalary')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'constraints': [models.UniqueConstraint(fields=('salary', 'code'), name='unique_emp_component_code')],
            },
        ),
    ]
