# Generated by Django 5.2.14 on 2026-06-16 17:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_organization_payroll_lop_policy'),
        ('payroll', '0002_employeesalarycomponent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='employer_pf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Employer PF contribution (cost to company; not deducted from net).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='category',
            field=models.CharField(choices=[('BASIC', 'Basic Salary'), ('HRA', 'HRA'), ('SPECIAL', 'Special Allowance'), ('MEDICAL', 'Medical Allowance'), ('TRAVEL', 'Travel Allowance'), ('BONUS', 'Bonus'), ('INCENTIVE', 'Incentives'), ('OVERTIME', 'Overtime'), ('PF', 'Provident Fund'), ('EMPLOYER_PF', 'Employer PF'), ('ESI', 'ESI'), ('PT', 'Professional Tax'), ('TAX', 'Income Tax'), ('LOAN', 'Loan Deduction'), ('ADVANCE', 'Salary Advance Recovery'), ('NOTICE', 'Notice Period Recovery'), ('OTHER', 'Other')], default='OTHER', max_length=12),
        ),
        migrations.CreateModel(
            name='EmployeeDeduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deduction_type', models.CharField(choices=[('ADVANCE', 'Salary Advance Recovery'), ('NOTICE', 'Notice Period Recovery'), ('OTHER', 'Other Deduction')], default='OTHER', max_length=12)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Per-cycle recovery amount.', max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_deductions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('PROCESSED', 'Payroll processed'), ('CALCULATED', 'Deductions calculated'), ('VIEWED', 'Deductions viewed'), ('EXPORTED', 'Report exported')], max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_audit_logs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
