# Generated by Django 5.2.14 on 2026-06-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payslip_employer_pf_alter_salarycomponent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarycomponent',
            name='category',
            field=models.CharField(choices=[('BASIC', 'Basic Salary'), ('HRA', 'HRA'), ('SPECIAL', 'Special Allowance'), ('MEDICAL', 'Medical Allowance'), ('TRAVEL', 'Travel Allowance'), ('BONUS', 'Bonus'), ('INCENTIVE', 'Incentives'), ('OVERTIME', 'Overtime'), ('PF', 'Provident Fund'), ('EMPLOYER_PF', 'Employer PF'), ('ESI', 'ESI'), ('PT', 'Professional Tax'), ('TAX', 'Income Tax'), ('LOAN', 'Loan Deduction'), ('ADVANCE', 'Salary Advance Recovery'), ('NOTICE', 'Notice Period Recovery'), ('LOP', 'Loss of Pay'), ('OTHER', 'Other')], default='OTHER', max_length=12),
        ),
    ]
