# Generated by Django 5.2.14 on 2026-06-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_repair_payslip_lop'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='last_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
