# Generated by Django 5.2.14 on 2026-07-12 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_gradepermission_permission_key'),
        ('organizations', '0018_shiftchange'),
        ('payroll', '0007_compliance_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeloan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending approval'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=12),
        ),
        migrations.AlterField(
            model_name='payrollauditlog',
            name='action',
            field=models.CharField(choices=[('PROCESSED', 'Payroll processed'), ('CALCULATED', 'Deductions calculated'), ('VIEWED', 'Deductions viewed'), ('EXPORTED', 'Report exported'), ('GENERATED', 'Payslip generated'), ('LOAN_APPROVED', 'Loan approved'), ('SETTINGS_UPDATED', 'Payroll settings updated')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='grade',
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_structures', to='grades.grade'),
        ),
        migrations.CreateModel(
            name='PayrollCycleConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('SEMI_MONTHLY', 'Semi-monthly'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=15)),
                ('payroll_day', models.PositiveSmallIntegerField(default=25, help_text='Day of the month payroll is processed.')),
                ('salary_day', models.PositiveSmallIntegerField(default=1, help_text='Day of the (following) month salary is credited.')),
                ('attendance_cutoff_day', models.PositiveSmallIntegerField(default=20)),
                ('leave_cutoff_day', models.PositiveSmallIntegerField(default=20)),
                ('approval_deadline_day', models.PositiveSmallIntegerField(default=23)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_cycle_config', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('decimal_precision', models.PositiveSmallIntegerField(default=2)),
                ('rounding_rule', models.CharField(choices=[('NONE', 'No rounding'), ('NEAREST', 'Round to nearest rupee'), ('UP', 'Always round up'), ('DOWN', 'Always round down')], default='NEAREST', max_length=10)),
                ('auto_payroll_enabled', models.BooleanField(default=False)),
                ('payslip_email_enabled', models.BooleanField(default=True)),
                ('approval_workflow_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_salary_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payroll.salarystructure')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_settings', to='organizations.organization')),
            ],
        ),
    ]
