# Generated by Django 5.2.14 on 2026-08-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_employeeloan_approved_at_employeeloan_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='payslip_format',
            field=models.CharField(choices=[('CLASSIC', 'Classic — detailed two-column'), ('MODERN', 'Modern — accent banner'), ('COMPACT', 'Compact — single table')], default='CLASSIC', max_length=10),
        ),
    ]
