# Generated by Django 5.2.14 on 2026-08-05 17:32

import apps.payroll.payslip_formats
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_payrollsettings_payslip_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollsettings',
            name='payslip_format',
            field=models.CharField(choices=apps.payroll.payslip_formats.payslip_format_choices, default='CLASSIC', max_length=20),
        ),
    ]
