# Generated by Django 5.2.14 on 2026-08-27 17:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_shiftchange'),
        ('payroll', '0010_alter_payrollsettings_payslip_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxComputation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year_start', models.DateField()),
                ('regime', models.CharField(choices=[('OLD', 'Old regime'), ('NEW', 'New regime')], default='NEW', max_length=8)),
                ('projected_gross', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_exemptions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('annual_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('rebate_applied', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cess', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tds_paid_till_date', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('months_remaining', models.PositiveSmallIntegerField(default=12)),
                ('monthly_tds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year_start', models.DateField(help_text='1 April of the FY this declaration covers.')),
                ('regime', models.CharField(choices=[('OLD', 'Old regime'), ('NEW', 'New regime')], default='NEW', max_length=8)),
                ('hra_rent_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total annual rent paid, for the HRA exemption.', max_digits=12)),
                ('metro_city', models.BooleanField(default=False, help_text='HRA exemption is 50% of basic in metros, 40% elsewhere.')),
                ('section_80c', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='EPF, PPF, ELSS, life insurance, tuition fees, principal repayment.', max_digits=12)),
                ('section_80d', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Health insurance premium — self, family and parents.', max_digits=12)),
                ('section_80ccd_1b', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Additional NPS contribution.', max_digits=12)),
                ('home_loan_interest', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Section 24(b) interest on a self-occupied house.', max_digits=12)),
                ('other_exemptions', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Any other approved exemption (80E, 80G, …).', max_digits=12)),
                ('other_income', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Income from other sources to include in the projection.', max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-financial_year_start', 'user__first_name'],
            },
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='cess_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('4'), help_text='Health and education cess applied on top of computed tax.', max_digits=5),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='rebate_87a_income_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('700000'), help_text='Taxable income at or below this gets the 87A rebate. 0 disables it.', max_digits=12),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='rebate_87a_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('25000'), help_text='Maximum 87A rebate. Caps at the tax due.', max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='taxconfiguration',
            constraint=models.UniqueConstraint(fields=('organization', 'financial_year_start', 'regime'), name='unique_tax_config_per_org_fy_regime'),
        ),
        migrations.AddField(
            model_name='taxcomputation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_computations', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='taxcomputation',
            name='payslip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_computation', to='payroll.payslip'),
        ),
        migrations.AddField(
            model_name='taxcomputation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_computations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_declarations', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_declarations_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_declarations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='taxdeclaration',
            constraint=models.UniqueConstraint(fields=('user', 'financial_year_start'), name='unique_tax_declaration_per_user_fy'),
        ),
    ]
