# Generated by Django 5.2.14 on 2026-08-28 08:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_shiftchange'),
        ('payroll', '0012_fix_new_regime_slabs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='deductor_name',
            field=models.CharField(blank=True, help_text='Name of the deductor as registered with TRACES. Defaults to the organization name.', max_length=150),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='employer_pan',
            field=models.CharField(blank=True, help_text="Employer's PAN.", max_length=15),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='tan_number',
            field=models.CharField(blank=True, help_text="Employer's TAN, e.g. BLRA12345C. Required on Form 16.", max_length=15),
        ),
        migrations.CreateModel(
            name='Form16Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year_start', models.DateField()),
                ('certificate_number', models.CharField(blank=True, max_length=40)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_exemptions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tds_deducted', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('balance_payable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form16_certificates_issued', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form16_certificates', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form16_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-financial_year_start', 'user__first_name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'financial_year_start'), name='unique_form16_per_user_fy')],
            },
        ),
    ]
