# Generated by Django 5.2.12 on 2026-05-28 18:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffboardingWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_working_day', models.DateField()),
                ('resignation_reason', models.CharField(choices=[('BETTER_OPPORTUNITY', 'Better opportunity'), ('PERSONAL', 'Personal reasons'), ('RELOCATION', 'Relocation'), ('HEALTH', 'Health'), ('RETIREMENT', 'Retirement'), ('TERMINATION', 'Termination'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CLEARANCE', 'Clearance in progress'), ('SETTLEMENT', 'Settlement'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboardings_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_workflows', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_working_day'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('letter_type', models.CharField(choices=[('EXPERIENCE', 'Experience letter'), ('RELIEVING', 'Relieving letter')], max_length=20)),
                ('content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters_generated', to=settings.AUTH_USER_MODEL)),
                ('offboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='lifecycle.offboardingworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback', models.TextField(blank=True)),
                ('reason_detail', models.TextField(blank=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('conducted_at', models.DateTimeField(blank=True, null=True)),
                ('offboarding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interview', to='lifecycle.offboardingworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joining_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In progress'), ('ORIENTATION', 'Orientation'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On hold')], default='IN_PROGRESS', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('welcome_sent', models.BooleanField(default=False)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardings_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_workflows', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joining_date'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('MANAGER', 'Manager'), ('TEAM', 'Team orientation'), ('SECURITY', 'Security')], default='HR', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], default='PENDING', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lifecycle.onboardingworkflow')),
            ],
            options={
                'ordering': ['due_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('AADHAAR', 'Aadhaar / Passport'), ('PAN', 'PAN Card'), ('RESUME', 'Resume'), ('EDUCATION', 'Educational certificates'), ('EXPERIENCE', 'Experience letters'), ('BANK', 'Bank details'), ('TAX', 'Tax documents'), ('ADDRESS', 'Address proof'), ('PHOTO', 'Profile photo'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(blank=True, upload_to='onboarding_documents/%Y/%m/')),
                ('verify_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('MISSING', 'Missing')], default='PENDING', max_length=20)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_verified', to=settings.AUTH_USER_MODEL)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lifecycle.onboardingworkflow')),
            ],
            options={
                'ordering': ['doc_type'],
            },
        ),
        migrations.CreateModel(
            name='AssetAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('ID_CARD', 'ID card'), ('EMAIL', 'Email account'), ('SYSTEM_ACCESS', 'System access'), ('MOBILE', 'Mobile / SIM'), ('ACCESSORY', 'Accessory')], max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ALLOCATED', 'Allocated'), ('RETURNED', 'Returned'), ('DAMAGED', 'Damaged'), ('MISSING', 'Missing'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('condition_notes', models.TextField(blank=True)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_allocations', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_allocations', to=settings.AUTH_USER_MODEL)),
                ('offboarding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_returns', to='lifecycle.offboardingworkflow')),
                ('onboarding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='lifecycle.onboardingworkflow')),
            ],
            options={
                'ordering': ['-allocated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrientationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('attended', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientation_sessions', to='lifecycle.onboardingworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=120)),
                ('policy_version', models.CharField(default='1.0', max_length=20)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('signature_note', models.CharField(blank=True, max_length=255)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acceptances', to='lifecycle.onboardingworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pending_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leave_encashment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reimbursements', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_approved', to=settings.AUTH_USER_MODEL)),
                ('offboarding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='lifecycle.offboardingworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='ClearanceApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('FINANCE', 'Finance'), ('ADMIN', 'Admin'), ('SECURITY', 'Security')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearances_approved', to=settings.AUTH_USER_MODEL)),
                ('offboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='lifecycle.offboardingworkflow')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('offboarding', 'department'), name='unique_clearance_dept_per_offboarding')],
            },
        ),
        migrations.AddConstraint(
            model_name='onboardingworkflow',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_onboarding_per_user'),
        ),
        migrations.AddConstraint(
            model_name='employeedocument',
            constraint=models.UniqueConstraint(fields=('onboarding', 'doc_type'), name='unique_doc_type_per_onboarding'),
        ),
        migrations.AddConstraint(
            model_name='policyacceptance',
            constraint=models.UniqueConstraint(fields=('onboarding', 'policy_name'), name='unique_policy_per_onboarding'),
        ),
    ]
