# Generated by Django 5.2.12 on 2026-05-29 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploader_role', models.CharField(blank=True, max_length=20)),
                ('department_name', models.CharField(blank=True, max_length=120)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(db_index=True, max_length=500)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('category', models.CharField(choices=[('DOCUMENT', 'Documents'), ('IMAGE', 'Images'), ('PDF', 'PDFs'), ('VIDEO', 'Videos'), ('PAYROLL', 'Payroll files'), ('EMPLOYEE', 'Employee documents'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('source_model', models.CharField(blank=True, max_length=80)),
                ('source_field', models.CharField(blank=True, max_length=80)),
                ('source_pk', models.CharField(blank=True, max_length=64)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_files', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('UPLOAD', 'Upload'), ('DELETE', 'Delete'), ('QUOTA_CHANGE', 'Quota change'), ('RESTRICT', 'Upload restricted'), ('SYNC', 'Index sync'), ('DOWNLOAD', 'Download')], max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_audit_logs', to='organizations.organization')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_audit_targets', to=settings.AUTH_USER_MODEL)),
                ('stored_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='storage.storedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStorageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_mb', models.PositiveIntegerField(default=0, help_text='0 = use org default')),
                ('uploads_restricted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quotas', to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_quota', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['organization', 'uploader_role'], name='storage_sto_organiz_db2ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['organization', 'category'], name='storage_sto_organiz_41f68a_idx'),
        ),
    ]
