# Generated by Django 5.2.14 on 2026-05-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='area',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='organization',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='established_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='language',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='organization',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='official_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_size',
            field=models.CharField(blank=True, choices=[('SOLO', '1'), ('SMALL', '2-50'), ('MEDIUM', '51-200'), ('LARGE', '201-1000'), ('ENTERPRISE', '1000+')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('SCHOOL', 'School')], default='COMPANY', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='schema_name',
            field=models.CharField(blank=True, max_length=63, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='organization',
            name='street_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
