# Generated by Django 5.2.14 on 2026-05-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_alternate_phone_organization_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='annual_revenue_range',
            field=models.CharField(blank=True, choices=[('UNDER_10L', 'Under 10L'), ('L10_50', '10L - 50L'), ('L50_1CR', '50L - 1Cr'), ('ABOVE_1CR', 'Above 1Cr')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='attendance_type',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('BIOMETRIC', 'Biometric'), ('HYBRID', 'Hybrid')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='biometric_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='board_type',
            field=models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('STATE', 'State Board'), ('IB', 'IB'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='branch_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='classes_available',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='company_type',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'Private Limited'), ('PUBLIC', 'Public Limited'), ('LLP', 'LLP'), ('PROPRIETORSHIP', 'Proprietorship'), ('NGO', 'NGO'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='current_hrms_used',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='date_format',
            field=models.CharField(blank=True, choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='departments_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='expected_employee_growth',
            field=models.CharField(blank=True, choices=[('SAME', 'No change'), ('GROW_10', 'Up to 10%'), ('GROW_25', '10-25%'), ('GROW_50', '25-50%'), ('GROW_100', '50%+')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='financial_year_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='gst_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='hostel_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='how_did_you_hear_about_us',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'Google Search'), ('SOCIAL', 'Social Media'), ('REFERRAL', 'Referral'), ('ADS', 'Advertisement'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='leave_management_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='library_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_users_allowed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='onboarding_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='onboarding_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='pain_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='organization',
            name='payroll_cycle',
            field=models.CharField(blank=True, choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='payroll_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='required_modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='organization',
            name='shift_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='signup_browser',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='signup_device',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='signup_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='storage_limit_mb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='total_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='total_teachers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='transport_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='week_start_day',
            field=models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('SUNDAY', 'Sunday')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='organization',
            name='currency',
            field=models.CharField(blank=True, default='INR', max_length=16),
        ),
        migrations.AlterField(
            model_name='organization',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=16),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_size',
            field=models.CharField(blank=True, choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('ENTERPRISE', 'Enterprise')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('COMPANY', 'Company'), ('SCHOOL', 'School'), ('COLLEGE', 'College')], default='COMPANY', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired')], default='TRIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='timezone',
            field=models.CharField(blank=True, default='Asia/Kolkata', max_length=64),
        ),
    ]
