# Generated by Django 5.2.14 on 2026-05-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_annual_revenue_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_type_other',
            field=models.CharField(blank=True, help_text='Specify when type is Other', max_length=120),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('COMPANY', 'Company / Corporate'), ('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('RESTAURANT', 'Restaurant / Food Service'), ('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic / Healthcare'), ('HOTEL', 'Hotel / Hospitality'), ('MANUFACTURING', 'Manufacturing'), ('IT_SERVICES', 'IT / Software Services'), ('CONSTRUCTION', 'Construction'), ('LOGISTICS', 'Logistics / Transport'), ('SCHOOL', 'School'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University'), ('NGO', 'NGO / Non-profit'), ('GOVERNMENT', 'Government'), ('OTHER', 'Other')], default='COMPANY', max_length=32),
        ),
    ]
