# Generated by Django 5.2.12 on 2026-05-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='hr_self_in_mark_attendance',
            field=models.BooleanField(default=False, help_text='When enabled, HR users appear in the mark-attendance table and can edit their own times.'),
        ),
    ]
