# Generated by Django 5.2 on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_organization_hr_self_in_mark_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="weekend_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SAT_SUN", "Saturday & Sunday (2 days)"),
                    ("SUN_ONLY", "Sunday only (1 day)"),
                    ("CUSTOM", "Custom fixed days"),
                    ("ROTATING_WEEKLY", "Rotating weekly"),
                    ("ROTATING_MONTHLY", "Rotating monthly"),
                    ("SHIFT_BASED", "Per shift / employee schedule"),
                ],
                default="SAT_SUN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="weekend_custom_days",
            field=models.CharField(
                blank=True,
                default="5,6",
                help_text="Comma-separated weekday numbers (0=Mon … 6=Sun) for CUSTOM policy.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="rotating_off_anchor",
            field=models.DateField(
                blank=True,
                help_text="Start date for rotating weekly off cycles.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="rotating_off_patterns",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of {"off_days": [5,6]} per cycle step.',
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="holidays_exclude_optional",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, optional holidays are not auto-excluded from leave/working-day counts.",
            ),
        ),
    ]
