# Generated by Django 5.2.12 on 2026-06-09 07:47

from django.db import migrations, models


# Consolidate to Basic / Professional / Growth.
_REMAP = {
    "FREE": "BASIC",
    "STARTER": "BASIC",
    "": "BASIC",
    "PREMIUM": "PROFESSIONAL",
    "ENTERPRISE": "GROWTH",
}


def remap_plans(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    for old, new in _REMAP.items():
        Organization.objects.filter(subscription_plan=old).update(subscription_plan=new)


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organization_leave_approval_workflow'),
    ]

    operations = [
        migrations.RunPython(remap_plans, reverse_noop),
        migrations.AlterField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('BASIC', 'Basic'), ('PROFESSIONAL', 'Professional'), ('GROWTH', 'Growth')], default='BASIC', max_length=20),
        ),
    ]
