# Generated by Django 5.2.12 on 2026-06-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_alter_organization_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='attendance_mode',
            field=models.CharField(choices=[('TIME_BASED', 'Time-Based'), ('STATUS_BASED', 'Status-Based')], default='TIME_BASED', help_text='TIME_BASED: HR/Admin record check-in/out times (hours, late, overtime auto-calculated). STATUS_BASED: attendance is marked with status values only (P/A/L/HD/H/WO), no time tracking.', max_length=20),
        ),
    ]
