# Generated by Django 5.2.14 on 2026-06-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_organization_attendance_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='leave_auto_approve_without_manager',
            field=models.BooleanField(default=True, help_text='When the approval chain resolves no approvers (e.g. employee has no reporting manager and no other steps are enabled), auto-approve the request. When disabled, the request is routed to HR (or the admin) instead of being auto-approved. Default preserves legacy behavior.'),
        ),
    ]
