# Generated by Django 5.2.14 on 2026-06-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_organization_leave_auto_approve_without_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='hr_role_display_name',
            field=models.CharField(blank=True, default='HR', help_text="Label shown wherever a user's role appears as 'HR' (e.g. Manager, Team Leader, Supervisor). Display only — the stored role and permissions are unchanged.", max_length=50),
        ),
    ]
