# Generated by Django 5.2.14 on 2026-06-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_organization_hr_role_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payroll_lop_policy',
            field=models.CharField(choices=[('ASSUME_PRESENT', 'Assume present (pay full unless explicitly absent)'), ('STRICT', 'Strict proration (pay by present ÷ working days)')], default='ASSUME_PRESENT', help_text='How unmarked attendance affects pay when running payroll. ASSUME_PRESENT pays full salary unless a day is explicitly marked absent; STRICT prorates pay by present ÷ working days.', max_length=20),
        ),
    ]
