# Generated by Django 5.2.12 on 2026-06-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_organization_payroll_lop_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='fy_start_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=4, help_text='Financial year start month (1=January … 12=December). Default: April (4).'),
        ),
    ]
