# Generated by Django 5.2.12 on 2026-06-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_absent_leave_type_priorities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='label',
            field=models.CharField(blank=True, help_text="Auto-generated if left blank (e.g. 'FY 2025-26').", max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='absent_attendance_policy',
            field=models.CharField(choices=[('NONE', 'No auto-deduction'), ('LEAVE', 'Deduct from a leave balance'), ('LOP', 'Deduct as Loss of Pay (LOP)')], default='NONE', help_text="When an employee is marked Absent, automatically deduct from a leave balance or record it as Loss of Pay. 'No auto-deduction' leaves balances untouched.", max_length=10),
        ),
    ]
